"""add functional index (lower post content)

Revision ID: 803612d9337d
Revises: 75f0dbdba277
Create Date: 2021-12-05 19:55:05.905897

"""

# revision identifiers, used by Alembic.
revision = '803612d9337d'
down_revision = '75f0dbdba277'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('post_lower_content_idx', 'post', [sa.text('lower(content)')], unique=False)
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('post_lower_content_idx', table_name='post')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
